# Generated by Django 6.0.1 on 2026-01-28 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_team_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='datetime',
            new_name='date_start',
        ),
        migrations.RenameField(
            model_name='tournament',
            old_name='datetime',
            new_name='date_start',
        ),
        migrations.AddField(
            model_name='match',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('COMING', 'À venir'), ('ONGOING', 'En cours'), ('DONE', 'Terminé')], default='COMING', max_length=20),
        ),
        migrations.AddField(
            model_name='tournament',
            name='auto_match_creation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='date_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Brouillon'), ('PUBLISHED', 'Publié'), ('ONGOING', 'En cours'), ('FINISHED', 'Terminé')], default='DRAFT', max_length=20),
        ),
    ]
