# Generated by Django 6.0.1 on 2026-01-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_rename_datetime_match_date_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='nb_team_matches',
            field=models.PositiveIntegerField(blank=True, help_text='Max matches per team for auto-creation', null=True),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='auto_match_creation',
            field=models.BooleanField(default=False),
        ),
    ]
