COUNTRIES = [
    # Name, capital city
    ("Émirats arabes unis", "Abou Dabi"),
    ("Nigeria", "Abuja"),
    ("Ghana", "Accra"),
    ("Turkménistan", "Achgabat"),
    ("Éthiopie", "Addis-Abeba"),
    ("Yemen", "Sanaa"),  # Contesté avec Aden
    ("Algérie", "Alger"),
    ("Niue", "Alofi"),
    ("Jordanie", "Amman"),
    ("Pays bas", "Amsterdam"),
    ("Andorre", "Andorre-la-Vieille"),
    ("Turquie", "Ankara"),
    ("Madagascar", "Antananarivo"),
    ("Samoa", "Apia"),
    ("Erythree", "Asmara"),
    ("Kazakhstan", "Astana"),
    ("Paraguay", "Asuncion"),
    ("Grece", "Athènes"),
    ("Cook", "Avarua"),
    ("Irak", "Bagdad"),
    ("Azerbaidjan", "Bakou"),
    ("Mali", "Bamako"),
    ("Brunei", "Bandar Seri Begawan"),
    ("Thaïlande", "Bangkok"),
    ("Centrafricaine république", "Bangui"),
    ("Gambie", "Banjul"),
    ("Saint christophe et nieves", "Basseterre"),
    ("Serbie", "Belgrade"),
    ("Belize", "Belmopan"),
    ("Allemagne", "Berlin"),
    ("Suisse", "Berne"),
    ("Liban", "Beyrouth"),
    ("Kirghizistan", "Bichkek"),
    ("Guinee bissau", "Bissau"),
    ("Afrique du Sud", "Pretoria"),  # 3 capitales : Bloemfontein, Le Cap, Pretoria
    ("Colombie", "Bogota"),
    ("Brésil", "Brasilia"),
    ("Slovaquie", "Bratislava"),
    ("Congo brazzaville", "Brazzaville"),
    ("Barbade", "Bridgetown"),
    ("Belgique", "Bruxelles"),
    ("Roumanie", "Bucarest"),
    ("Hongrie", "Budapest"),
    ("Argentine", "Buenos Aires"),
    ("Burundi", "Gitega"),
    ("Égypte", "Caire"),
    ("Australie", "Canberra"),
    ("Venezuela", "Caracas"),
    ("Sainte lucie", "Castries"),
    ("Montenegro", "Podgorica"),
    ("Moldavie", "Chisinau"),
    ("Guinee equatoriale", "Ciudad de la Paz"),
    ("Sri Lanka", "Sri Jayawardenapura Kotte"),
    ("Honduras", "Comayagüela"),  # Avec Tegucigalpa
    ("Guinee", "Conakry"),
    ("Danemark", "Copenhague"),
    ("Bénin", "Porto-Novo"),  # Cotonou
    ("Sénégal", "Dakar"),
    ("Syrie", "Damas"),
    ("Bangladesh", "Dacca"),
    ("Tanzanie", "Dodoma"),  # Dar es Salam
    ("Timor-Leste", "Dili"),
    ("Djibouti", "Djibouti"),
    ("Soudan du Sud", "Djouba"),
    ("Qatar", "Doha"),
    ("Tadjikistan", "Douchanbé"),
    ("Irlande", "Dublin"),
    ("Arménie", "Erevan"),
    ("Sierra Leone", "Freetown"),
    ("Tuvalu", "Vaiaku"),  # Atol: Funafuti
    ("Botswana", "Gaborone"),
    ("Guyana", "Georgetown"),
    ("Guatemala", "Guatemala"),
    ("Vietnam", "Hanoï"),
    ("Zimbabwe", "Harare"),
    ("Cuba", "Havane"),
    ("Finlande", "Helsinki"),
    ("Salomon", "Honiara"),
    ("Pakistan", "Islamabad"),
    ("Indonesie", "Jakarta"),
    # ("Israël", "Tel Aviv"),  # Trop sensible
    # ("Palestine", "Ramallah"), # Trop sensible
    ("Afghanistan", "Kaboul"),
    ("Ouganda", "Kampala"),
    ("Nepal", "Katmandou"),
    ("Soudan", "Khartoum"),
    ("Ukraine", "Kiev"),
    ("Rwanda", "Kigali"),
    ("Jamaïque", "Kingston"),
    ("Saint vincent et les grenadines", "Kingstown"),
    ("Congo kinshasa", "Kinshasa"),
    ("Palaos", "Ngerulmud"),
    ("Koweit", "Koweït"),
    ("Malaisie", "Kuala Lumpur"),
    ("Gabon", "Libreville"),
    ("Malawi", "Lilongwe"),
    ("Perou", "Lima"),
    ("Portugal", "Lisbonne"),
    ("Slovénie", "Ljubljana"),
    ("Togo", "Lomé"),
    ("Royaume uni", "Londres"),
    ("Angola", "Luanda"),
    ("Zambie", "Lusaka"),
    ("Luxembourg", "Luxembourg"),
    ("Espagne", "Madrid"),
    ("Marshall iles", "Delap-Uliga-Darrit"),
    ("Maldives", "Malé"),
    ("Nicaragua", "Managua"),
    ("Bahreïn", "Manama"),
    ("Philippines", "Manille"),
    ("Mozambique", "Maputo"),
    ("Oman", "Mascate"),
    ("Lesotho", "Maseru"),
    ("Eswatini", "Mbabane"),
    ("Mexique", "Mexico"),
    ("Bielorussie", "Minsk"),
    ("Somalie", "Mogadiscio"),
    ("Monaco", "Monaco"),
    ("Liberia", "Monrovia"),
    ("Uruguay", "Montevideo"),
    ("Comores", "Moroni"),
    ("Russie", "Moscou"),
    ("Kenya", "Nairobi"),
    ("Bahamas", "Nassau"),
    ("Birmanie", "Naypyidaw"),
    ("Tchad", "N'Djaména"),
    ("Inde", "New Delhi"),
    ("Niger", "Niamey"),
    ("Chypre", "Nicosie"),
    ("Mauritanie", "Nouakchott"),
    ("Tonga", "Nuku'alofa"),
    ("Norvege", "Oslo"),
    ("Canada", "Ottawa"),
    ("Burkina Faso", "Ouagadougou"),
    ("Mongolie", "Oulan-Bator"),
    ("Micronesie", "Palikir"),
    ("Panama", "Panama"),
    ("Suriname", "Paramaribo"),
    ("France", "Paris"),
    ("Bolivie", "La Paz"),  # Ou Sucre# Trop sensible
    ("Chine", "Pékin"),
    ("Cambodge", "Phnom Penh"),
    ("Papouasie nouvelle guinée", "Port Moresby"),
    ("Haiti", "Port-au-Prince"),
    ("Trinite et tobago", "Port-d'Espagne"),
    ("Maurice", "Port-Louis"),
    ("Vanuatu", "Port-Vila"),
    ("Tchéquie", "Prague"),
    ("Cap vert", "Praia"),
    ("Corée du Nord", "Pyongyang"),
    ("Équateur", "Quito"),
    ("Maroc", "Rabat"),
    ("Islande", "Reykjavik"),
    ("Lettonie", "Riga"),
    ("Arabie saoudite", "Riyad"),
    ("Italie", "Rome"),
    ("Dominique", "Roseau"),
    ("Antigua et barbuda", "Saint John's"),
    ("Dominicaine république", "Saint-Domingue"),
    ("Grenade", "Saint-Georges"),
    ("Saint marin", "Saint-Marin"),
    ("Costa Rica", "San José"),
    ("Salvador", "San Salvador"),
    ("Chili", "Santiago"),
    ("Sao tome et principe", "São Tomé"),
    ("Bosnie-Herzégovine", "Sarajevo"),
    ("Corée du Sud", "Sejong"),
    ("Singapour", "Singapour"),
    ("Macédoine du Nord", "Skopje"),
    ("Bulgarie", "Sofia"),
    ("Suède", "Stockholm"),
    ("Fidji", "Suva"),
    ("Ouzbékistan", "Tachkent"),
    ("Estonie", "Tallinn"),
    ("Kiribati", "Tarawa-Sud"),
    ("Georgie", "Tbilissi"),
    ("Iran", "Téhéran"),
    ("Bhoutan", "Thimphou"),
    ("Albanie", "Tirana"),
    ("Japon", "Tokyo"),
    ("Libye", "Tripoli"),
    ("Tunisie", "Tunis"),
    ("Liechtenstein", "Vaduz"),
    ("Malte", "Valette"),
    ("Pologne", "Varsovie"),
    ("Vatican", "Vatican"),
    ("Seychelles", "Victoria"),
    ("Autriche", "Vienne"),
    ("Laos", "Vientiane"),
    ("Lituanie", "Vilnius"),
    ("États unis", "Washington"),
    ("Nouvelle zélande", "Wellington"),
    ("Namibie", "Windhoek"),
    ("Côte divoire", "Yamoussoukro"),
    ("Cameroun", "Yaoundé"),
    ("Nauru", "Yaren"),
    ("Croatie", "Zagreb"),
]
